import os
from pathlib import Path

base_dir = Path("d:/CVS")

# List of files to touch
files_to_create = [
    "LICENSE",
    ".gitignore",
    "docker-compose.yml",
    "docs/API_Documentation.md",
    "docs/Database_Design.md",
    "docs/Project_Roadmap.md",
    "docs/User_Manual.md",
    "docs/Deployment_Guide.md",
    "frontend/assets/css/theme.css",
    "frontend/assets/css/dashboard.css",
    "frontend/assets/css/responsive.css",
    "frontend/assets/css/animations.css",
    "frontend/assets/js/auth.js",
    "frontend/assets/js/api.js",
    "frontend/assets/js/dashboard.js",
    "frontend/assets/js/test.js",
    "frontend/assets/js/charts.js",
    "frontend/layouts/auth_layout.html",
    "frontend/layouts/dashboard_layout.html",
    "frontend/layouts/blank_layout.html",
    "frontend/pages/auth/login.html",
    "frontend/pages/auth/forgot_password.html",
    "frontend/pages/auth/reset_password.html",
    "frontend/pages/super_admin/dashboard.html",
    "frontend/pages/super_admin/colleges.html",
    "frontend/pages/super_admin/staff.html",
    "frontend/pages/super_admin/reports.html",
    "frontend/pages/super_admin/subscriptions.html",
    "frontend/pages/super_admin/settings.html",
    "frontend/pages/college_admin/dashboard.html",
    "frontend/pages/college_admin/students.html",
    "frontend/pages/college_admin/departments.html",
    "frontend/pages/college_admin/courses.html",
    "frontend/pages/college_admin/tests.html",
    "frontend/pages/college_admin/analytics.html",
    "frontend/pages/staff/dashboard.html",
    "frontend/pages/staff/lesson_plan.html",
    "frontend/pages/staff/mcq.html",
    "frontend/pages/staff/coding.html",
    "frontend/pages/staff/assignments.html",
    "frontend/pages/staff/attendance.html",
    "frontend/pages/student/dashboard.html",
    "frontend/pages/student/profile.html",
    "frontend/pages/student/mcq_practice.html",
    "frontend/pages/student/coding_practice.html",
    "frontend/pages/student/results.html",
    "frontend/pages/student/resume.html",
    "frontend/pages/student/certificates.html",
    "backend/routes/colleges.py",
    "backend/routes/students.py",
    "backend/routes/staff.py",
    "backend/routes/tests.py",
    "backend/routes/coding.py",
    "backend/routes/reports.py",
    "backend/routes/analytics.py",
    "backend/routes/notifications.py",
    "database/seed_data.sql",
    "database/procedures.sql",
    "database/triggers.sql",
    "database/views.sql",
    "scripts/create_admin.py",
    "scripts/seed_database.py",
    "scripts/backup_database.py",
    "scripts/restore_database.py",
]

# List of empty directories to create
dirs_to_create = [
    "frontend/assets/images",
    "frontend/assets/icons",
    "frontend/assets/fonts",
    "frontend/components/navbar",
    "frontend/components/sidebar",
    "frontend/components/footer",
    "frontend/components/cards",
    "frontend/components/tables",
    "frontend/components/modals",
    "frontend/components/charts",
    "backend/config",
    "backend/auth",
    "backend/middleware",
    "backend/controllers",
    "backend/services",
    "backend/repositories",
    "backend/models",
    "backend/schemas",
    "backend/database",
    "backend/ai/cheating_detection",
    "backend/ai/ai_answer_detection",
    "backend/ai/analytics",
    "backend/ai/recommendation",
    "backend/compiler/judge0",
    "backend/compiler/docker_runner",
    "backend/compiler/execution",
    "backend/exports",
    "backend/uploads",
    "backend/logs",
    "backend/utils",
    "database/migrations",
    "database/backups",
    "storage/profile_photos",
    "storage/certificates",
    "storage/reports",
    "storage/resumes",
    "storage/question_imports",
    "tests/frontend",
    "tests/backend",
    "tests/api",
    "tests/security",
    "deployment/nginx",
    "deployment/ssl",
    "deployment/scripts",
    "deployment/docker",
]

for d in dirs_to_create:
    (base_dir / d).mkdir(parents=True, exist_ok=True)

for f in files_to_create:
    file_path = base_dir / f
    file_path.parent.mkdir(parents=True, exist_ok=True)
    if not file_path.exists():
        file_path.touch()

print("Structure generation completed successfully.")
